[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.4.0-beta-dev.27"
hdk = "=0.3.0-beta-dev.31"
serde = "1.0"
chrono = { version = "0.4.34", default-features = false, features = ["clock", "std"] }
pgp = "0.10.2"
hex = "0.4.3"
regex = "1.10.3"

[workspace.dependencies.trusted]
path = "dnas/trusted/zomes/coordinator/trusted"

[workspace.dependencies.trusted_integrity]
path = "dnas/trusted/zomes/integrity/trusted"
