[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.4.0-beta-dev.24"
hdk = "=0.3.0-beta-dev.28"
serde = "1.0"

[workspace.dependencies.trusted]
path = "dnas/trusted/zomes/coordinator/trusted"

[workspace.dependencies.trusted_integrity]
path = "dnas/trusted/zomes/integrity/trusted"
