name: "Test"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          install_url: https://releases.nixos.org/nix/nix-2.25.4/install

      - uses: cachix/cachix-action@v15
        with:
          name: esl-checked
          extraPullNames: holochain-ci
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Lint Rust (hApp)
        run: |
          nix develop --command cargo fmt --all -- --check
          nix develop --command cargo clippy -- --deny warnings

      - name: Lint Rust (CLI)
        run: |
          cd checked_cli
          nix develop --command cargo fmt --all -- --check
          nix develop --command cargo clippy -- --deny warnings

      - name: Run Rust tests
        run: |
          nix develop --command npm run test:unit

      - name: Install NPM dependencies
        run: |
          nix develop --command npm ci

      - name: Build UI
        run: |
          nix develop --command npm --workspace ui build

      - name: Run Tryorama tests
        run: |
          nix develop --command npm run test:integration

      - name: Run CLI tests
        run: |
          nix develop --command npm run test:cli

  cli-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.5'

      - uses: Swatinem/rust-cache@v2

      - name: Run CLI tests
        run: |
          cargo install holochain_cli@0.4.2 --locked
          
          cargo build --release --target wasm32-unknown-unknown
          hc app pack workdir --recursive
          
          # Tests are independent but sweettest is so resource hungry that they run slower in parallel.
          cd ./checked_cli
          cargo test --release -- --test-threads=1
